"use client";
import {useRef,useState} from "react";
import styles from "./public-page.module.css";
const topics=["App support","Waitlist","Privacy request","Account deletion","Partnerships"];
export function ContactForm({initialTopic="App support"}:{initialTopic?:string}) {
 const [topic,setTopic]=useState(initialTopic),[email,setEmail]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[website,setWebsite]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reference,setReference]=useState('');
 const lock=useRef(false),id=useRef('');
 async function submit(event:React.FormEvent){event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');
 try{if(!navigator.onLine)throw Error('You’re offline. Reconnect to send. Your message is still here.');if(!id.current)id.current=crypto.randomUUID();const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.current,topic,email,name,message,website}),signal:AbortSignal.timeout(15000)});const b=await r.json();if(!r.ok)throw Error(b.error||'Please try again.');setReference(b.reference);}catch(e){setError(e instanceof Error && e.name!=='TimeoutError'?e.message:'Sending took too long. Retry with the same message or email us directly.');}finally{lock.current=false;setBusy(false);}}
 if(reference)return <div className={styles.success} role="status"><h2>Message sent.</h2><p>We’ll reply to {email}. {topic==='Account deletion'?'This starts a request; your account has not been deleted. We’ll verify account ownership first.':'Your message is with the Rezlee team.'}</p><p>Reference: {reference}</p><p>You have not been added to marketing emails.</p></div>;
 return <form onSubmit={submit} className={styles.form}><label className={styles.field}>What can we help with?<select value={topic} onChange={e=>setTopic(e.target.value)} disabled={busy}>{topics.map(t=><option key={t}>{t}</option>)}</select></label><label className={styles.field}>Email address<input type="email" required autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label className={styles.field}>Name <span>(optional)</span><input autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label className={styles.field}>Your message<textarea required minLength={10} maxLength={3000} value={message} onChange={e=>setMessage(e.target.value)} disabled={busy} aria-describedby="contact-guidance"/></label><div className={styles.trap} aria-hidden="true"><label>Website<input tabIndex={-1} autoComplete="off" value={website} onChange={e=>setWebsite(e.target.value)}/></label></div><p id="contact-guidance">Please don’t include passwords, verification codes, full account numbers or documents. We use these details to respond to your request. <a href="/privacy#contact">Privacy details</a>.</p>{error?<p className={styles.error} role="alert">{error}</p>:null}<button disabled={busy} type="submit">{busy?'Sending…':'Send message'}</button><p>Your message stays on this page if sending fails. It is not saved if you close the page.</p></form>;
}
