-- Phase 11: Guided household issue help.
-- Safe to run in Supabase SQL Editor after Homeowner OS foundation.

alter table public.repair_issues add column if not exists category text;
alter table public.repair_issues add column if not exists location text;
alter table public.repair_issues add column if not exists renter_owner_context text;
alter table public.repair_issues add column if not exists likely_causes jsonb not null default '[]'::jsonb;
alter table public.repair_issues add column if not exists recommended_steps jsonb not null default '[]'::jsonb;
alter table public.repair_issues add column if not exists safety_notes jsonb not null default '[]'::jsonb;
alter table public.repair_issues add column if not exists escalation_recommendation text;
alter table public.repair_issues add column if not exists related_task_id uuid references public.maintenance_tasks(id) on delete set null;
alter table public.repair_issues add column if not exists related_project_id uuid references public.projects(id) on delete set null;
alter table public.repair_issues add column if not exists related_provider_id uuid references public.providers(id) on delete set null;
alter table public.repair_issues add column if not exists resolved_at timestamptz;

update public.repair_issues
set
  location = coalesce(location, area),
  category = coalesce(category, 'general_repair'),
  renter_owner_context = coalesce(renter_owner_context, 'both'),
  likely_causes = coalesce(likely_causes, '[]'::jsonb),
  recommended_steps = coalesce(recommended_steps, '[]'::jsonb),
  safety_notes = coalesce(safety_notes, '[]'::jsonb),
  related_project_id = coalesce(related_project_id, project_id)
where
  location is null
  or category is null
  or renter_owner_context is null
  or likely_causes is null
  or recommended_steps is null
  or safety_notes is null
  or related_project_id is null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'repair_issues_urgency_check'
      and conrelid = 'public.repair_issues'::regclass
  ) then
    alter table public.repair_issues
      add constraint repair_issues_urgency_check
      check (urgency in ('low', 'medium', 'high', 'urgent', 'monitor', 'soon'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'repair_issues_status_check'
      and conrelid = 'public.repair_issues'::regclass
  ) then
    alter table public.repair_issues
      add constraint repair_issues_status_check
      check (status in (
        'open',
        'next_steps_ready',
        'task_created',
        'waiting_on_landlord',
        'waiting_on_professional',
        'resolved',
        'dismissed'
      ));
  end if;
end;
$$;

create index if not exists repair_issues_category_idx on public.repair_issues(category);
create index if not exists repair_issues_urgency_idx on public.repair_issues(urgency);
create index if not exists repair_issues_related_task_id_idx on public.repair_issues(related_task_id);
create index if not exists repair_issues_resolved_at_idx on public.repair_issues(resolved_at);

comment on column public.repair_issues.category is 'Guided issue category such as plumbing, electrical, heating_cooling, appliance, internet, pest, leak_water_damage, safety, or general_repair.';
comment on column public.repair_issues.location is 'Where the issue is happening in the home or place.';
comment on column public.repair_issues.likely_causes is 'Rules-based possible causes shown carefully without claiming diagnosis.';
comment on column public.repair_issues.recommended_steps is 'Safe first steps and follow-up suggestions generated by rules.';
comment on column public.repair_issues.safety_notes is 'Safety and escalation cautions for the issue.';
comment on column public.repair_issues.escalation_recommendation is 'Plain-language guidance on when to call a landlord, property manager, or qualified professional.';
comment on column public.repair_issues.related_task_id is 'Care task created from this household issue.';
comment on column public.repair_issues.resolved_at is 'Timestamp when the issue was marked resolved.';

notify pgrst, 'reload schema';
